# Generated by Django 3.2 on 2021-06-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
